### ISSUE TITLE
Fix random `OSError: [Errno 12] Cannot allocate memory`

### ISSUE THREAD

**Issue by ikus060** [ikus060/rdiffweb#52]
A user report having issue to restore files. User get the following problem:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
        response.body = self.handler()
      File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.0-py2.7.egg/rdiffweb/page_restore.py", line 113, in index
        file_path_b = path_obj.restore(file_b, restore_date, usetar != "T")
      File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.0-py2.7.egg/rdiffweb/librdiff.py", line 860, in restore
        output)
      File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.0-py2.7.egg/rdiffweb/librdiff.py", line 750, in _execute
        parms, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1153, in _execute_child
        self.pid = os.fork()
    OSError: [Errno 12] Cannot allocate memory

The memory on the server is not used. 
Have a look at 
http://stackoverflow.com/questions/1367373/python-subprocess-popen-oserror-errno-12-cannot-allocate-memory

**Comment by ikus060** [comment]
Fixed.
