### ISSUE TITLE
"access denied" when accessing path containing a symlink?

### ISSUE THREAD

**Issue by sudoman** [ikus060/rdiffweb#61]
````
# ls -ld /backup
lrwxrwxrwx 1 root root 18 Sep 24  2014 /backup -> /srv/backup-online
````

If i set the root directory for admin to the following, i get errors for every backup in that directory: `/backup/backupninja/`

````
[2015-09-24 16:13:04,750][ERROR  ][root] invalid user path rdiff-backup/server.website.com
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/page_locations.py", line 48, in _get_parms_for_page
    repo_obj = librdiff.RdiffRepo(user_root_b, encode_s(user_repo))
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/librdiff.py", line 449, in __init__
    self.root_path = RdiffPath(self)
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/librdiff.py", line 661, in __init__
    self._check()
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/librdiff.py", line 675, in _check
    raise AccessDeniedError()
AccessDeniedError: Access denied.
````

**Comment by ikus060** [comment]
Yep, for security reason, rdiffweb doesn't follow symbolic link unless the symbolic link point to a directory under a user repo.

e.g.:
* My user root directory: `/home/ikus060`
* My repository: `/home/ikus060/backup-ikus060-laptop`
* There is a symbolic link `/home/ikus060/backup-ikus060-laptop/data/myfile -> ../coucou`
This will work since ../coucou is part of `/home/ikus060/backup-ikus060-laptop`

Failure to do so open a very wide security breach, since the backup repository may contains a symbolic link pointing to any location on the server. Thus, this would allow the user to access any file on the server.

e.g.:
* There is a symbolic link `/home/ikus060/backup-ikus060-laptop/data/myfile -> /home
If rdiffweb follow symbolic link blindly, users may access `/home` when browsing `/home/ikus060/backup-ikus060-laptop/data/myfile`
