### ISSUE TITLE
rdiffweb crash

### ISSUE THREAD

**Issue by sudoman** [ikus060/rdiffweb#63]
this crash happens whenever i click the "status" link at the top.

````
[2015-09-25 13:11:27,226][INFO   ][cherrypy.error.139895416701904] [25/Sep/2015:13:11:27] HTTP
Request Headers:
  CONNECTION: keep-alive
  REFERER: http://server.website.org:8080/
  HOST: server.website.org:8080
  UPGRADE-INSECURE-REQUESTS: 1
  Remote-Addr: 192.168.0.222
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
  COOKIE: session_id=517dd714e616c625afabc7bc97e52fb8b14d9166
  ACCEPT-LANGUAGE: en-US,en;q=0.8
  ACCEPT-ENCODING: gzip, deflate, sdch
[2015-09-25 13:11:27,226][ERROR  ][cherrypy.error.139895416701904] [25/Sep/2015:13:11:27] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/page_status.py", line 52, in index
    userMessages = self._get_recent_user_messages(failures != "")
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/page_status.py", line 144, in _get_recent_user_messages
    asOfDate, None)
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/page_status.py", line 170, in _getUserMessages
    "errors": backup.errors} for backup in backups]
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/librdiff.py", line 216, in errors
    self._repo._error_logs[self.date].read()
  File "/usr/local/lib/python2.7/dist-packages/rdiffweb-0.7.2-py2.7.egg/rdiffweb/librdiff.py", line 276, in read
    return self._open().read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x1303741 != 0x563362ffL
````

**Comment by ikus060** [comment]
Hum

I would be worried about your data integrity. It failed during CRC Gzip verification. Most probably one of the gzip file open by rdiffweb is corrupt. You should try to validate the repository using `rdiff-backup --check-destination-dir`

BTW, the "Status" page will be removed from rdiffweb 0.8.0 (next version). After some this information will be spread across different page.
