### ISSUE TITLE
Downloading items from rdiffweb fails

### ISSUE THREAD

**Issue by geekbozu** [ikus060/rdiffweb#68]
Downloading items from the web interface fails using rdiffweb.
Downloaded items return a 0 Size file. 
Python Version 3.7.3
rdiffweb version 1.2.1
```
[2020-02-10 19:27:09,473][DEBUG  ][192.168.1.14][admin][CP Server Thread-5][rdiffweb.core.librdiff] get directory entries for [b'/home/pi/rdiffbackup/David/Plots']
[2020-02-10 19:27:10,492][DEBUG  ][192.168.1.14][admin][CP Server Thread-6][rdiffweb.controller.filter_authentication] setting request.login to UserObject(1)
[2020-02-10 19:27:10,493][DEBUG  ][192.168.1.14][admin][CP Server Thread-6][rdiffweb.controller.page_restore] restoring [b'admin/David/Plots/1.png'][1581359210]
[2020-02-10 19:27:10,506][INFO   ][127.0.0.1][anonymous][RestoreThread-16][rdiffweb.core.librdiff] execute rdiff-backup --restore-as-of=1581359210 b'/home/pi/rdiffbackup/David/Plots/1.png' b'/tmp/rdiffweb_restore_cmpeykyn'
[2020-02-10 19:27:10,523][ERROR  ][127.0.0.1][anonymous][RestoreThread-16][rdiffweb.core.librdiff] restore failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rdiffweb/core/librdiff.py", line 1030, in _async
    output)
  File "/usr/local/lib/python3.7/dist-packages/rdiffweb/core/librdiff.py", line 824, in execute
    env=env)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: b'rdiff-backup': b'rdiff-backup'

```

**Comment by ikus060** [comment]
Hi Tim,

Look like you don't have a version of rdiff-backup installed or available from in the PATH.

Could you provide more detail about how you installed rdiff-backup ?

Otherwise, make sure you have follow the steps documented here: https://github.com/ikus060/rdiffweb/blob/master/doc/installation.md

**Comment by geekbozu** [comment]
rdiff-backup shows upon my path for root and my normal user
I installed rdiff-backup via the tar.gz package as the version available for the RPI on apt is very outdated (1.2.8)
Installation instructions for rdiff-web were followed verbatim

Thanks for getting back to me :)

**Comment by ikus060** [comment]
Take note version `1.9.0b` is a beta version and may not be compatible with rdiffweb.
I'm still in process of testing everything with that version. You may prefer the more stable version that come from apt (version 1.2.8). rdiffweb is well tested using this version.

Seconds, I have a better understanding of your issue.
Will check if I can create a path for you. It's a bit delicate to be honest. The PATH variable is default to /usr/bin/,/bin to avoid picking the same python version as rdiffweb.

**Comment by geekbozu** [comment]
Everything else has been working fine so far actually, Shows the right info/data etc.

I'm not sure why picking the same python version would matter? I would love to know why just to understand  :)

let me just try installing rdiff-backup to /usr/bin if that solves it I can live with it :)

**Comment by geekbozu** [comment]
That fixed it. I would be willing to say this is closable with just a foot note that the development versions of rdiff-backup need to be installed to /usr/bin instead of /usr/local/bin

**Comment by geekbozu** [comment]
That commit solves the issue on my machine as well.

**Comment by ikus060** [comment]
@geekbozu 
May you confirm: you tested the rdiffweb with 592ff2c with your setup and it's working ?

**Comment by geekbozu** [comment]
I can confirm that solves the issue.
